global:
  scrape_interval: 5s
  evaluation_interval: 5s

# 警报规则文件配置
rule_files:
  # - "alert_rules.yml"

# 抓取目标配置
scrape_configs:
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']
  - job_name: 'gogc_test'
    static_configs:
      - targets: ['host.docker.internal:8080']  # 适用于 Mac/Windows, Linux 需要修改为实际 IP
    scrape_interval: 1s  # 更频繁地抓取 GC 指标 