version: '3.8'

services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # 接收来自 collector 的 model.proto
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.81.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC 接收器
      - "4318:4318"   # OTLP http 接收器
      - "8888:8888"   # Prometheus metrics 暴露
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - jaeger 