// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: monitor/server/grpc/hello.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状态枚举
type Status int32

const (
	Status_UNKNOWN Status = 0
	Status_SUCCESS Status = 1
	Status_ERROR   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "ERROR",
	}
	Status_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"ERROR":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_server_grpc_hello_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_monitor_server_grpc_hello_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_monitor_server_grpc_hello_proto_rawDescGZIP(), []int{0}
}

// 请求消息
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // 用户名
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // 自定义消息
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_monitor_server_grpc_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_server_grpc_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_monitor_server_grpc_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 响应消息
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`                       // 问候语
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // 时间戳
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"` // 服务器名称
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=hello.Status" json:"status,omitempty"`        // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_monitor_server_grpc_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_server_grpc_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_monitor_server_grpc_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

func (x *HelloResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HelloResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *HelloResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

var File_monitor_server_grpc_hello_proto protoreflect.FileDescriptor

const file_monitor_server_grpc_hello_proto_rawDesc = "" +
	"\n" +
	"\x1fmonitor/server/grpc/hello.proto\x12\x05hello\"\xb8\x01\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\bmetadata\x18\x03 \x03(\v2!.hello.HelloRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\rHelloResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x06status\x18\x04 \x01(\x0e2\r.hello.StatusR\x06status*-\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x022\x88\x02\n" +
	"\fHelloService\x124\n" +
	"\x05Hello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00\x12<\n" +
	"\vHelloStream\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x000\x01\x12B\n" +
	"\x11HelloClientStream\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00(\x01\x12@\n" +
	"\rHelloBiStream\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00(\x010\x01B\x18Z\x16monitor/server/grpc/pbb\x06proto3"

var (
	file_monitor_server_grpc_hello_proto_rawDescOnce sync.Once
	file_monitor_server_grpc_hello_proto_rawDescData []byte
)

func file_monitor_server_grpc_hello_proto_rawDescGZIP() []byte {
	file_monitor_server_grpc_hello_proto_rawDescOnce.Do(func() {
		file_monitor_server_grpc_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_server_grpc_hello_proto_rawDesc), len(file_monitor_server_grpc_hello_proto_rawDesc)))
	})
	return file_monitor_server_grpc_hello_proto_rawDescData
}

var file_monitor_server_grpc_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_monitor_server_grpc_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_monitor_server_grpc_hello_proto_goTypes = []any{
	(Status)(0),           // 0: hello.Status
	(*HelloRequest)(nil),  // 1: hello.HelloRequest
	(*HelloResponse)(nil), // 2: hello.HelloResponse
	nil,                   // 3: hello.HelloRequest.MetadataEntry
}
var file_monitor_server_grpc_hello_proto_depIdxs = []int32{
	3, // 0: hello.HelloRequest.metadata:type_name -> hello.HelloRequest.MetadataEntry
	0, // 1: hello.HelloResponse.status:type_name -> hello.Status
	1, // 2: hello.HelloService.Hello:input_type -> hello.HelloRequest
	1, // 3: hello.HelloService.HelloStream:input_type -> hello.HelloRequest
	1, // 4: hello.HelloService.HelloClientStream:input_type -> hello.HelloRequest
	1, // 5: hello.HelloService.HelloBiStream:input_type -> hello.HelloRequest
	2, // 6: hello.HelloService.Hello:output_type -> hello.HelloResponse
	2, // 7: hello.HelloService.HelloStream:output_type -> hello.HelloResponse
	2, // 8: hello.HelloService.HelloClientStream:output_type -> hello.HelloResponse
	2, // 9: hello.HelloService.HelloBiStream:output_type -> hello.HelloResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_monitor_server_grpc_hello_proto_init() }
func file_monitor_server_grpc_hello_proto_init() {
	if File_monitor_server_grpc_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_server_grpc_hello_proto_rawDesc), len(file_monitor_server_grpc_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_server_grpc_hello_proto_goTypes,
		DependencyIndexes: file_monitor_server_grpc_hello_proto_depIdxs,
		EnumInfos:         file_monitor_server_grpc_hello_proto_enumTypes,
		MessageInfos:      file_monitor_server_grpc_hello_proto_msgTypes,
	}.Build()
	File_monitor_server_grpc_hello_proto = out.File
	file_monitor_server_grpc_hello_proto_goTypes = nil
	file_monitor_server_grpc_hello_proto_depIdxs = nil
}
